### ISSUE TITLE
Citations to add

### ISSUE THREAD

**Issue by timothydmorton** [dfm/peerless#23]
Re: future spectroscopic follow-up of long-P planets:

http://adsabs.harvard.edu/abs/2015ApJ...814..154D
http://adsabs.harvard.edu/abs/2016ApJ...826L...7D

**Comment by ericagol** [comment]
Also perhaps http://arxiv.org/abs/1607.06892

These are later type stars & much longer period, but nevertheless constrain the long-period giant planet frequency as well.
