### ISSUE TITLE
did EBCatalog change?

### ISSUE THREAD

**Issue by timothydmorton** [dfm/peerless#5]
I'm re-running my prediction calculations to reproduce what I had before, and I see that the number of EBs that I should be expecting in my calibration simulations given all the detected EBs and the fraction of the target stars we've selected has changed (`n_exp` from cell 12 in the version of the predictions notebook currently on github).  In the previous calculations `n_exp` had been ~104, and now it's ~138.  Have you changed the EB catalog in the last few months?  Just making sure I understand what's new.

**Comment by dfm** [comment]
It did. A more recent version of the catalog came out so I updated.

Another good idea would be to run the script: `scripts/peerless-targets` to download the target list and then use

```
from peerless.catalogs import TargetCatalog
targets = TargetCatalog().df
```

to load the target list to make sure that we have the same selection.

**Comment by timothydmorton** [comment]
OK great, I figured this was the case; just wanted to make sure.
