### ISSUE TITLE
simulated observed planet population is low

### ISSUE THREAD

**Issue by timothydmorton** [dfm/peerless#7]
So I'm trying to simulate the observed population of planets according to your inferred occurrence rate, and I'm coming up short.  Just wanted to report, since in order for me to trust my simulated population of binaries I should be able to generate ~30 detected planets given the occurrence given in the paper.  With an input population taken as in Table 5, the following is the number of detections I generate over 100 trials, both with a cut of SNR > 15 and without.

![image](https://cloud.githubusercontent.com/assets/1895387/16778626/a468cc82-4823-11e6-8c42-b5a8cf639a25.png)

This is a substantial factor smaller than I'd need it to be for comfort.  I'll be investigating my simulations for problems, but just wanted to let you know.  I've pushed my updated [predictions notebook](https://github.com/dfm/peerless/blob/master/prediction/prediction.ipynb).

**Comment by timothydmorton** [comment]
OK, I realize that I am assigning uniform periods and radii, instead of log-uniform.  Let me see if that fixes things.

**Comment by timothydmorton** [comment]
OK, here is the new figure, which looks a bit better:

![image](https://cloud.githubusercontent.com/assets/1895387/16783286/416630a6-4838-11e6-88a1-91d984bd4e2d.png)

So, here, the typical simulation nets about 20 planets; however, typically only about 7 of them have SNR > 15.  Here's the SNR distribution of the simulated dectections (SNR > 15) compared to the SNR distribution of your candidates:

![image](https://cloud.githubusercontent.com/assets/1895387/16783519/38ab74b6-4839-11e6-8934-006c20702c5f.png)

I'm not sure the best way to reconcile this discrepancy. Thoughts?

**Comment by timothydmorton** [comment]
OK, I realize that I'm not selecting candidates to have R < Rjup, so this is certainly part of it.  My current selection is `accept_bic and accept_time and num_peaks <= 2`

**Comment by timothydmorton** [comment]
OK, now selecting for the 18 candidates with R < Rjup, this is how the SNR distributions compare.  

![image](https://cloud.githubusercontent.com/assets/1895387/16784933/17b93840-4840-11e6-91ab-201c980e238e.png)

Presumably the SNR > 15 threshold in the simulations is not super accurate, since probably a lot of the signals that would have had lower SNR would have gotten vetoed (e.g. not strong enough preferred over the box model).  However, building in this veto with a more sophisticated detection model in my simulations would just result in a smaller number of planets, making the discrepancy larger.

**Comment by dfm** [comment]
Sorry for the delay!

The final candidates to use are in `results/fits.csv` and these have `depth` and `duration` constraints from the MCMC fits. This file has 16 candidates in it. How are you computing the SNR in these plots?

I could probably re-parameterize the injections to depth/duration to generate a completeness function in that space if you think that might help.

**Comment by dfm** [comment]
P.S. I'm in Germany so I'm about to go to bed but I'll take a better look at this in the morning.

**Comment by timothydmorton** [comment]
No worries about timing; I'm on the west coast, so we're pretty off phase here.

Yeah, I was wondering whether or not I wanted to try to implement the actual censoring used, and I probably will eventually want to do this in `exosyspop`, so I suppose I might try that---though it would be simplest for me to approximate the 1-d efficiency as a function of SNR (though I understand that might not capture all the salient features of the detection pipeline).

I'm computing SNR as the mean depth of the fitted trapezoid shape / cdpp (interpolated at the transit total duration), times the sqrt of the number of transits.  Is this close enough to your definition to be comparable?

**Comment by timothydmorton** [comment]
Never mind about the SNR question; I can take your trapezoid fits and use the exact same definition that I do to compare.

**Comment by timothydmorton** [comment]
OK, so using my definition of SNR, here is how the 16 candidate SNRs compare with the simulated distribution.

![image](https://cloud.githubusercontent.com/assets/1895387/16818745/2c8aa7cc-48fe-11e6-99fa-e988b59b8627.png)

Still not sure what to think about the low predicted number of detected planets, though.

**Comment by timothydmorton** [comment]
Can you double-check here that my sampling radius/period from your population model is correct?

``` python
from exosyspop.populations import PlanetPopulation, REARTH

import astropy.constants as const
RJUP = const.R_jup.cgs
RSUN = const.R_sun.cgs

class LongPeriodPlanetPopulation(PlanetPopulation):
    """
    Poisson Population in two bins: 0.1-0.4 RJup and 0.4-1.0 RJup

    From 2 to 25 years, with beta eccentricity distribution
    """
    min_period = 2*365.25
    max_period = 25*365.25

    param_names = ('Gam1', 'Gam2', 'beta_a', 'beta_b')
    default_params = {'Gam1':0.24, 'Gam2':0.18,
                      'beta_a':1.12, 'beta_b':3.09}

    def _sample_period(self, N):
        lo = np.log(self.min_period)
        hi = np.log(self.max_period)
        logp = np.random.random(N)*(hi - lo) + lo
        return np.exp(logp)

    def _sample_Np(self, N):
        Gam1, Gam2 = self._get_params(['Gam1', 'Gam2'])
        N_pl = Gam1 + Gam2 # Sum of both bins is total rate
        return np.random.poisson(N_pl, size=N)

    def _sample_Rp(self, N):
        Gam1, Gam2 = self._get_params(['Gam1', 'Gam2'])

        # Assign radii uniformly in each bin, with appropriate ratio given to each bin
        f1 = Gam1 / (Gam1 + Gam2)
        u = np.random.random(N)
        in_1 = u < f1
        in_2 = u >= f1
        N1 = in_1.sum()
        N2 = in_2.sum()

        Rp = np.ones(N)
        lo1, hi1 = np.log(0.1), np.log(0.4)
        lo2, hi2 = np.log(0.4), np.log(1)
        Rp[in_1] = np.exp(np.random.random(N1)*(hi1 - lo1) + lo1)
        Rp[in_2] = np.exp(np.random.random(N2)*(hi2 - lo2) + lo2)
        return Rp * RJUP/RSUN
```

**Comment by dfm** [comment]
The one issue is that those gammas should probably be integrated. The
numbers in the paper are dN/dlnP dlnR. To get the expected number in a bin,
you need to multiply by the volume. That should probably have the right
sign...

I'd have an easier time explaining things if you were generating _more_
planets because my completeness should be much more conservative than the
prescription you're using.

**Comment by dfm** [comment]
Also. I just found a bug that meant that I was underestimating your `Gam1`. It should actually be 0.4.

**Comment by timothydmorton** [comment]
Of course!  That looks like it does it.  (The 0.24->0.4 bug didn't make much difference in detected planets because most of those are undetectable.)

![image](https://cloud.githubusercontent.com/assets/1895387/16844884/beda8884-499b-11e6-8b79-774e2a67a4d0.png)

**Comment by dfm** [comment]
Awesome! That looks better.

**Comment by ericagol** [comment]
What is the X-axis of the plot?

Eric Agol
Astronomy Professor
University of Washington

**Comment by timothydmorton** [comment]
Sorry-- x-axis here is number of planet detections.  This is a histogram of 100 simulations based on the best-fit inferred population model (and a toy detection model).

**Comment by timothydmorton** [comment]
The point of this exercise is to demonstrate that the simulations that I use to create synthetic populations of EB and BEB false positives works to also simulate sensible synthetic populations of planets.
