### ISSUE TITLE
Some candidate KICIDs not in targets list?

### ISSUE THREAD

**Issue by timothydmorton** [dfm/peerless#8]
There seem to be a handful of candidates from `candidates.csv` whose KIC IDs are not in the targets table:

10271691
10613792
11038446
12204153
6751029
7987086
7971363
8540644
8584610
9159119
9730194
9701988

I'm grabbing the targets table with

``` python
from peerless.catalogs import TargetCatalog
targets = TargetCatalog().df
```

What's going on?  Am I missing something?

**Comment by dfm** [comment]
The `candidates.csv` file is from a previous run but all I've updated is the EB catalog and all of these have been added in the most recent update of the Villanova catalog. You can get the right candidate list by using

```
import pandas as pd
from peerless.catalogs import TargetCatalog
targets = TargetCatalog().df
cands = pd.read_csv("results/candidates.csv")
cands = pd.merge(cands, targets, how="inner", left_on="kicid", right_on="kepid", suffixes=["", "stlr"])
```

Or just by looking at the `results/fits.csv` file.

Also: the final acceptance criterion is that the `accept` column is `True`. This includes an impact parameter (V-shaped) cut that I didn't include previously.

**Comment by timothydmorton** [comment]
OK great, thanks!
